apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: /configs
    repoURL: "https://github.com/AliHaine/ayagmur-ception"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true