apiVersion: v1
kind: Service
metadata:
  name: will
  namespace: dev
spec:
  type: NodePort
  selector:
    app: will
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 31888